// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvN12slMFlXPg8RcexTeGRn1My2kgVaA8',
    appId: '1:880648187658:android:d3c78a8ecc19b77b2c14f3',
    messagingSenderId: '880648187658',
    projectId: 'joongshim-uji',
    storageBucket: 'joongshim-uji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi3kKBPAuBC52Mv5XtTUW5OdsxwQxkORc',
    appId: '1:880648187658:ios:3e158153ce6c99d22c14f3',
    messagingSenderId: '880648187658',
    projectId: 'joongshim-uji',
    storageBucket: 'joongshim-uji.firebasestorage.app',
    iosClientId:
        '880648187658-6643bsvub7h17tp0rhp7d6q0hiuebmhh.apps.googleusercontent.com',
    iosBundleId: 'com.uji.joongshim',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvq-MUCIvED0GVF63kPvcbk-HC0ZX4wg0',
    appId: '1:880648187658:web:ca2f2856f8b736e32c14f3',
    messagingSenderId: '880648187658',
    projectId: 'joongshim-uji',
    authDomain: 'joongshim-uji.firebaseapp.com',
    storageBucket: 'joongshim-uji.firebasestorage.app',
  );
}
